### PR TITLE
Add new inscription ID

### PR DESCRIPTION
**Pull request by boka340**

### CODE REVIEW

**Comment by elocremarc** [comment]
You have to add your inscriptionId not the one from the readme

**Comment by boka340** [comment]
Inscription ID of what?…. Any ghost ordinal?


Sent from Yahoo Mail for iPhone


On Saturday, July 1, 2023, 1:23 AM, Eloc ***@***.***> wrote:




You have to add your inscriptionId not the one from the readme

**Comment by elocremarc** [comment]
@boka340 you need to inscribe the manifesto from [here](https://github.com/cypherpunklab/manifesto/blob/main/manifesto.html)

See the instructions https://github.com/cypherpunklab/manifesto/tree/main#inscribe

**Comment by elocremarc** [comment]
Closing this PR. Make a new one if you end up inscribing your own

**Pull request closed without merging**
