### PR TITLE
Add new inscription ID

### PR DESCRIPTION
**Pull request by sfhoo**

### CODE REVIEW

**Comment by sfhoo** [comment]
I did a checksum with sha256 and all three inscriptions were valid. It seem ordinals.com now pull the inscription and display so your script was failing.

**Comment by elocremarc** [comment]
Hey so were only need people submit 1 inscription Id. Please update your Pr to just have 1.

**Comment by sfhoo** [comment]
Inscription were in their wallet. So just have them do the merge themselves?

**Comment by elocremarc** [comment]
Yeah part of it is getting people to learn basics of github

**Comment by sfhoo** [comment]
cool, I'll have them pull and check in.

**Comment by elocremarc** [comment]
Cool appreciate it. I merged all the other PRs in so you can probably deal with the conflict on yours I assume as well?

**Comment by sfhoo** [comment]
Yup, no problem. So limited one per account?

**Comment by sfhoo** [comment]
Updated to only one entry. @elocremarc

**Pull request closed without merging**
