### PR TITLE
CypherPunk Ghosts Application 

### PR DESCRIPTION
**Pull request by tommyflower**

### CODE REVIEW

**Comment by tommyflower** [comment]
LFG

**Comment by tommyflower** [comment]
with that Tutorial video i learned basics of coding, thank you Ghosts !

**Review by elocremarc — CHANGES_REQUESTED** [review]
You used the inscriptionId in the example please inscribe your own and add that instead. 
https://github.com/cypherpunklab/manifesto#inscribe

**Comment by tommyflower** [comment]
so now i just need to delete this pull request and do another one changning the inscription name?

**Comment by elocremarc** [comment]
You can or you can  just change line 25 where you put the wrong one with yours.

**Comment by tommyflower** [comment]
so i can put the inscription i want? or i need to put specific ones? sorry for the disturb.

**Comment by elocremarc** [comment]
You need to inscribe it your own and check if its valid
https://github.com/cypherpunklab/manifesto#inscribe

**Comment by tommyflower** [comment]
oh yeah so basically i just need to inscribe the text (in the 13,982,020 inscription), once inscribed i get the id and i put it, right?

**Comment by elocremarc** [comment]
See the inscructions. Download the file [here](https://github.com/cypherpunklab/manifesto/blob/main/manifesto.html)

**Comment by tommyflower** [comment]
look https://www.ord.io/14555207 this is my inscription but when i put the id it says "manifesto is not valid"

**Comment by tommyflower** [comment]
image   now it gives me that tipe of error...

**Comment by elocremarc** [comment]
@tommyflower Someone already submitted that one. Were you front ran or do you submit under a different account?
https://github.com/cypherpunklab/manifesto/pull/75

**Review by elocremarc — APPROVED** [review]

**Pull request merged**
