### PR TITLE
400a8f4f368c0d6b0c2d623663089d7c16952160d0aa8599ea1b88dc4533c8e1i0

### PR DESCRIPTION
**Pull request by graybranch77**

### CODE REVIEW

**Comment by elocremarc** [comment]
You need to resolve the conflicts before merging.

**Comment by graybranch77** [comment]
What's the best way to do this sir?
I'm new to coding and would love some help here if you have the time.

**Comment by elocremarc** [comment]
Goto revolve conflicts
https://github.com/cypherpunklab/manifesto/pull/45/conflicts

You got to delete the stuff on line 21,23,27

image

**Comment by graybranch77** [comment]
Thanks. This is my first commit lol. How's it look?

**Review by elocremarc — APPROVED** [review]
Looks good great work!
Edit: it has conflicts still haha

**Comment by graybranch77** [comment]
Thank you friend ! I appreciate your help 🙏

**Pull request merged**
